name: Deploy finances backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run remote commands over SSH
        uses: appleboy/ssh-action@v1
        with:
          username: ${{ secrets.SSH_USER }}
          host: "${{ secrets.SSH_HOST }}"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/homelab/docker/finances-backend
            git pull origin main
            docker compose -f deployment/docker-compose.yml down
            docker compose -f deployment/docker-compose.yml up -d --build \
              -e DB_NAME=${DB_NAME} \
              -e DB_USER=${DB_USER} \
              -e DB_PASSWORD=${DB_PASSWORD} \
              -e DB_HOST=${DB_HOST} \
              -e DB_PORT=${DB_PORT} \
              -e DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
